on:
  push:
  pull_request:
  schedule:
    - cron: "16 7 * * *" # every day at 7:16 am
name: Crawl Makelaarsland.nl
jobs:
  scheduled:
    if: ${{ github.event_name == 'schedule'}}
    environment: default
    name: default
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.1.15"
      - name: Poetry install
        run: poetry install
      - name: Poetry run main
        run: poetry run python main.py makelaarsland
        env:
          MAKELAARSLAND_BUCKET: ${{ secrets.MAKELAARSLAND_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: lassebenni/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you

  throttled:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    environment: default
    name: throttled
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.1.15"
      - name: Poetry install
        run: poetry install
      - name: Poetry run main
        run: poetry run python main.py makelaarsland --full_run=False

  # great_expectations:
  #   - uses: ./github/workflows/great_expectations.yml
  #     secrets: inherit