on:
  push:
  pull_request:
  schedule:
    - cron: "16 7 * * *" # every day at 7:16 am
name: Crawl Makelaarsland.nl
jobs:
  scheduled:
    if: ${{ github.event_name == 'schedule'}}
    environment: default
    name: default
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@master
      - name: pip install
        run: pip install -r requirements.txt
      - name: run makelaarsland crawler
        run: python main.py makelaarsland
        env:
          MAKELAARSLAND_USERNAME: ${{ secrets.MAKELAARSLAND_USERNAME }}
          MAKELAARSLAND_PASSWORD: ${{ secrets.MAKELAARSLAND_PASSWORD }}
          MAKELAARSLAND_LISTING_ID: ${{ secrets.MAKELAARSLAND_LISTING_ID }}
      - uses: lassebenni/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you

  throttled:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    environment: default
    name: throttled
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@master
      - name: pip install
        run: pip install -r requirements.txt
      - name: run makelaarsland crawler
        run: python main.py makelaarsland 1
        env:
          MAKELAARSLAND_USERNAME: ${{ secrets.MAKELAARSLAND_USERNAME }}
          MAKELAARSLAND_PASSWORD: ${{ secrets.MAKELAARSLAND_PASSWORD }}
          MAKELAARSLAND_LISTING_ID: ${{ secrets.MAKELAARSLAND_LISTING_ID }}
