on:
  push:
  pull_request:
  schedule:
    - cron: "16 7 * * *" # every day at 7:16 am
name: Crawl Makelaarsland.nl
jobs:
  scheduled:
    if: ${{ github.event_name == 'schedule'}}
    environment: default
    name: default
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@master
      - name: pip install
        run: pip install -r requirements.txt
      - name: run makelaarsland crawler
        run: python main.py makelaarsland
        env:
          MAKELAARSLAND_USERNAME: ${{ secrets.MAKELAARSLAND_USERNAME }}
          MAKELAARSLAND_PASSWORD: ${{ secrets.MAKELAARSLAND_PASSWORD }}
          MAKELAARSLAND_LISTING_ID: ${{ secrets.MAKELAARSLAND_LISTING_ID }}
      - uses: lassebenni/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you

  throttled:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    environment: default
    name: throttled
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@master
      - name: pip install
        run: pip install -r requirements.txt
      - name: run makelaarsland crawler
        run: python main.py makelaarsland 1
        env:
          MAKELAARSLAND_USERNAME: ${{ secrets.MAKELAARSLAND_USERNAME }}
          MAKELAARSLAND_PASSWORD: ${{ secrets.MAKELAARSLAND_PASSWORD }}
          MAKELAARSLAND_LISTING_ID: ${{ secrets.MAKELAARSLAND_LISTING_ID }}

  great_expectations_validation:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      # Clone the contents of the repository
      - uses: actions/checkout@main

        # Run Great Expectations and deploy Data Docs to Netlify
        # In this example, we have configured a Checkpoint called "locations.rds.chk".
      - name: Run Great Expectation Checkpoints
        id: ge
        # Use @v0.x instead of @main to pin to a specific version, e.g. @v0.2
        uses: great-expectations/great_expectations_action@main
        with:
          CHECKPOINTS: "my_checkpoint" # This can be a comma-separated list of Checkpoints
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

        # Comment on PR with link to deployed Data Docs if there is a failed Checkpoint, otherwise don't comment.
      - name: Comment on PR
        if: ${{ always() }}
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (process.env.FAILURE_FLAG == 1 ) {
              msg = `Failed Great Expectations Checkpoint(s) \`${process.env.FAILED_CHECKPOINTS}\` detected for: ${process.env.SHA}.  Corresponding Data Docs have been generated and can be viewed [here](${process.env.URL}).`;
              console.log(`Message to be emitted: ${msg}`);
              github.issues.createComment({
                 issue_number: context.issue.number,
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 body: msg 
               });
            }
        env:
          URL: "${{ steps.ge.outputs.netlify_docs_url }}"
          FAILED_CHECKPOINTS: ${{ steps.ge.outputs.failing_checkpoints }}
          SHA: ${{ github.sha }}
          FAILURE_FLAG: ${{ steps.ge.outputs.checkpoint_failure_flag }}
