on:
  pull_request:
  schedule:
    - cron:  '16 7 * * *' # every day at 7:16 am
name: Pull Data and Build
jobs:
  build:
    environment: default
    name: Build
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@master
      - name: pip install
        run: pip install -r requirements.txt
      - name: run crawler
        run: python crawl.py
        env:
          MAKELAARSLAND_USERNAME: ${{ secrets.MAKELAARSLAND_USERNAME }}
          MAKELAARSLAND_PASSWORD: ${{ secrets.MAKELAARSLAND_PASSWORD }}
          MAKELAARSLAND_LISTING_ID: ${{ secrets.MAKELAARSLAND_LISTING_ID }}
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
